name: Contract CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: smart-contracts

    steps:
      - uses: actions/checkout@v3
      - name: Install packages
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - run: yarn --ignore-scripts
        shell: bash
      - name: Run Tests
        run: yarn hardhat test
      # - name: Create local node and deploy
      #   run: |
      #     yarn hardhat node &
      #     yarn hardhat run scripts/deploy.ts --network localhost